config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  get 'login/index'
  get 'login/new'
  post 'login/create'
  post 'login/authenticate'
  get 'login/edit'
  patch 'login/update'
  delete 'login/destroy'
  get 'admin/panel'
  post 'admin/post_user'
  post 'admin/post_medium'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medium.rb
class Medium < ApplicationRecord
end

app/models/shared_medium.rb
class SharedMedium < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def panel
    @users =  User.all.limit(10)
    @media =  Medium.all.limit(10)
  end

  def post_user
    # puts params[:name],  params[:email],  params[:number]
    User.create(name: params[:name], email: params[:email], number: params[:number])
    redirect_to "/admin/panel"
  end

  def post_medium
    Medium.create(name: params[:name], owner_id: params[:owner_id], location: params[:location])
    redirect_to "/admin/panel"
  end

  
  def upload_file
    # puts params
    file = Medium.new
    file.owner_id = 1
    file.name = "goback.txt"
    file.location = params[:file]
    file.save

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @user = User.find_by(id: 1)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
    @user.number = params[:number]
    @user.password = params[:password]
    @user.password_confirmation = params[:password]
    
    if @user.save
      redirect_to homepage_index_path
    else
      render json: {
        key: 'Failure',
        message: 'Something went wrong! Please try again'
    }, status: :forbidden
    end
  end

  def authenticate
    @user = User.find_by_email(params[:email])
    if !@user
      render json: {
          key: 'username',
          message: 'No user can be found with that Username'
      }, status: :forbidden
    else    
      isAuthed = @user.try(:authenticate, params['password'])
      if !isAuthed
          render json: {
              key: 'password',
              message: 'Incorrect Password'
              }, status: :forbidden
      else
          render json: {
              id: @user.id,
              username: @user.name,
          }
      end
    end
  end

  def update
  end

  def destroy
  end

  def new
  end

  def edit
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/admin/panel.html.erb
<h1>Admin#create_user</h1>
<form  action="/admin/post_user" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="name">First name:</label>
  <input type="text" id="name" name="name"><br><br>
  <label for="email">Email:</label>
  <input type="text" id="email" name="email"><br><br>
  <label for="number">Phone number:</label>
  <input type="number" id="number" name="number"><br><br>


  <input type="submit" value="Submit">
</form>
 <br><br>

 <% @users.each do |user| %>
 <%=  user.id %>
 <%=  user.name %>
 <%=  user.email %>
 <%=  user.number %>
 <br>
 <% end %>

 <br><br>

<h1>Admin#create_medium</h1>
<form  action="/admin/post_medium" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="name">File name:</label>
  <input type="text" id="name" name="name"><br><br>
  <label for="owner_id">Owner id:</label>
  <input type="integer" id="owner_id" name="owner_id"><br><br>
  <label for="location">Path:</label>
  <input type="text" id="location" name="location"><br><br>

  <input type="submit" value="Submit">
</form>
 <br><br>
  <% @media.each do |medium| %>
 <%=  medium.name %>
 <%=  medium.owner_id %>
 <%=  medium.location %>
 <br>
 <% end %>

  <br><br>

<h1>Admin#Upload_file</h1>
<form  action="/admin/upload_file" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="location">Path:</label>
  <input type="file" id="file" name="file"><br><br>
  <input type="submit" value="Submit">
</form>
 <br><br>

app/views/homepage/index.html.erb
<h1>Welcome <%=@user.name%>!</h1>
<h3>This your panel</h3>
<br><br><br>
<h2>Wow such empty!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DriveClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<h1>Login#index</h1>
<form  action="/login/authenticate" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<label for="email">Enter your email:</label>
<input type="email" id="email" name="email"><br><br>
  <label for="passowrd">Password:</label>
  <input type="password" id="password" name="password"><br><br>

  <input type="submit" value="Login">
</form>
 <br><br>
 <br><br>
 <p>Not a member yet? <%= link_to "Sign up!", login_new_path %></p>
 

app/views/login/new.html.erb
<h1>Register#index</h1>
<form  action="/login/create" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<label for="name">Enter your name:</label>
<input type="name" id="name" name="name"><br><br>
<label for="email">Enter your email:</label>
<input type="email" id="email" name="email"><br><br>
    <label for="phone">Enter your phone number:</label>
    <input type="tel" id="phone" name="phone" pattern="[0-9]{10}"><br><br>
  <label for="password">Password:</label>
  <input type="password" id="password" name="password"><br><br>

  <input type="submit" value="Register">
</form> 